---
format_version: '11'
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
project_type: ios

pipelines:
  test_pipeline:
    stages:
    - stage_1: {}
    - stage_2: {}

stages:
  stage_1:
    workflows:
    - DecisionMaking: {}
  stage_2:
    workflows:
    - testVble: {}

workflows:
  DecisionMaking:
    description: |
      Wworkflow to test using env vbles across stages
    steps:
    - activate-ssh-key@4: {}
    - git-clone@7: {}
    - cache-pull@2: {}
    - swiftlint-extended@1:
        inputs:
        - linting_path: $BITRISE_SOURCE_DIR
     - share-pipeline-variable@1:
        inputs:
        - variables: RUN_UI_TESTS=true
  testVble:
    description:
      workflow to test
    steps:
    - git-clone@7: {}
    - cache-pull@2: {}
    - script@1.1:
        title: check it warnings
        inputs:
        - content: |
            #!/bin/bash -e
            set -e
            echo $RUN_UI_TESTS
  App2:
    description: |
      The workflow the tests
    steps:
    - activate-ssh-key@4: {}
    - git-clone@7: {}
    - cache-pull@2: {}
    - swiftlint-extended@1:
        inputs:
        - linting_path: $BITRISE_SOURCE_DIR
    - script@1.1:
        title: check it warnings
        inputs:
        - content: |
            #!/bin/bash -e
            set -e
            echo "$SWIFTLINT_REPORT"

            if [ ! -z "$SWIFTLINT_REPORT" ] ;then
            # The file is not-empty.
                echo "Failing build since there are swiftlint errors"
                exit 1
            fi
    - swiftlint@0:
        inputs:
        - linting_path: $BITRISE_SOURCE_DIR
    - script@1.1:
        title: Run Worflow for app2
        inputs:
        - content: |
            echo "Running script for APP2"
    - cache-push@2: {}
    - deploy-to-bitrise-io@2: {}
  App1:
    description: |
      The workflow  the tests.
    steps:
    - activate-ssh-key@4: {}
    - git-clone@7:
        inputs:
        - clone_depth: 1
    - cache-pull@2: {}
    - swiftlint-extended@1:
        inputs:
        - linting_path: $BITRISE_SOURCE_DIR
    - script@1.1:
        title: Run Worflow for app1
        inputs:
        - content: |
            echo "Running script for APP1"
    - cache-push@2: {}
    - deploy-to-bitrise-io@2: {}
  RootDir:
    description: |
      This workflow only runs when files in root dir are changed
    steps:
    - activate-ssh-key@4: {}
    - git-clone@7:
        inputs:
        - clone_depth: "10"
    - script@1.1:
        title: Decide which workflow should run
        inputs:
        - content: |
            echo "Running RootDir workflow"
  WorkflowDecisionMaking:
    description: |
      The workflow to run when code not related to app has changed in PR and / or main
    steps:
    - activate-ssh-key@4: {}
    - git-clone@7:
        inputs:
        - clone_depth: "10"
    - script@1.1:
        title: Decide which workflow should run
        run_if: not .IsPR
        inputs:
        - content: |
            echo "Decision making to run workflow"
            echo "Commit on origin/main"
            LATEST_COMMIT_ON_MAIN_ORIGIN=`git log -n 1 origin/main --pretty=format:"%H"`
            echo $LATEST_COMMIT_ON_MAIN_ORIGIN

            echo "Commit on main branch"
            LATEST_COMMIT_ON_MAIN_PR=`git log -n 2 origin/main --pretty=format:"%H" | tail -n 1`
            echo $LATEST_COMMIT_ON_MAIN_PR

            FILES_CHANGED=`git diff --name-only $LATEST_COMMIT_ON_MAIN_PR $LATEST_COMMIT_ON_MAIN_ORIGIN`

            echo "$FILES_CHANGED"
            echo "Based on the files changed, run corresponding workflow"
            STR=$FILES_CHANGED

            SUB_APP1="TestApp1"
            SUB_APP2="TestApp2"

            buildApp1(){
            curl -X POST 'https://api.bitrise.io/v0.1/apps/afc64c84ebbc2f3c/builds' \
            -H 'accept: application/json' \
            -H "authorization: $TOKEN" \
            -H 'Content-Type: application/json' \
            -d '{
            "build_params": {
            "branch": "main",
            "workflow_id": "App1"
            },
            "hook_info": {
            "type": "bitrise"
            }
            }'
            }

            buildApp2(){
            curl -X POST 'https://api.bitrise.io/v0.1/apps/eccdc15b339b352c/builds' \
            -H 'accept: application/json' \
            -H "authorization: $TOKEN" \
            -H 'Content-Type: application/json' \
            -d '{
            "build_params": {
            "branch": "main",
            "workflow_id": "App2"
            },
            "hook_info": {
            "type": "bitrise"
            }
            }'
            }

            runCommonBuildApp2(){
            curl -X POST 'https://api.bitrise.io/v0.1/apps/eccdc15b339b352c/builds' \
            -H 'accept: application/json' \
            -H "authorization: $TOKEN" \
            -H 'Content-Type: application/json' \
            -d '{
            "build_params": {
            "branch": "main",
            "workflow_id": "RootDir"
            },
            "hook_info": {
            "type": "bitrise"
            }
            }'
            }

            runCommonBuildApp1(){
            curl -X POST 'https://api.bitrise.io/v0.1/apps/afc64c84ebbc2f3c/builds' \
            -H 'accept: application/json' \
            -H "authorization: $TOKEN" \
            -H 'Content-Type: application/json' \
            -d '{
            "build_params": {
            "branch": "main",
            "workflow_id": "RootDir"
            },
            "hook_info": {
            "type": "bitrise"
            }
            }'
            }

            if [[ "$STR" == *"$SUB_APP1"* ]] && [[ "$STR" == *"$SUB_APP2"* ]] ; then
                echo "Both app changed run WF1 and WF2"
                buildApp1
                buildApp2
            elif [[ "$STR" == *"$SUB_APP1"* ]]; then
                echo "TestApp1 changed run WF1"
                buildApp1
            elif [[ "$STR" == *"$SUB_APP2"* ]]; then
                echo "TestApp2 changed run WF2"
                buildApp2
            else
                echo "only Root changed run Common"
                runCommonBuildApp2
                runCommonBuildApp1           
            fi
    - cache-pull@2: {}
    - cache-push@2: {}
    - deploy-to-bitrise-io@2: {}
trigger_map:
- push_branch: main
  workflow: WorkflowDecisionMaking
- pull_request_source_branch: app1-*
  workflow: App1
- pull_request_source_branch: app2-*
  workflow: App2
- pull_request_source_branch: rootDir-*
  workflow: RootDir
- pull_request_source_branch: *
  pipeline: test_pipeline
meta:
  bitrise.io:
    stack: osx-xcode-14.1.x-ventura
